'use client'

import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import { formatCurrency } from '@/lib/utils'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1a1a1a' },
  title: { fontSize: 16, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 11, color: '#6b7280', marginBottom: 16 },
  cards: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  card: { flex: 1, border: '1 solid #e5e7eb', borderRadius: 4, padding: 8 },
  cardLabel: { fontSize: 9, color: '#6b7280', marginBottom: 2 },
  cardValue: { fontSize: 13, fontFamily: 'Helvetica-Bold' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: '6 4', borderBottom: '1 solid #e5e7eb' },
  tableRow: { flexDirection: 'row', padding: '5 4', borderBottom: '1 solid #f3f4f6' },
  th: { fontFamily: 'Helvetica-Bold', fontSize: 9, color: '#374151' },
  c1: { flex: 2 }, c2: { flex: 2 }, c3: { flex: 2 }, c4: { width: 50, textAlign: 'right' }, c5: { width: 70, textAlign: 'right' }, c6: { width: 50, textAlign: 'center' },
})

type Props = {
  date: string
  summary: { count: number; total_revenue: number; cash_revenue: number; credit_revenue: number; sales: any[] }
}

function DailyDocument({ date, summary }: Props) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.title}>Daily Sales Report</Text>
        <Text style={styles.subtitle}>Date: {date} · Generated by Lahiru Hardware</Text>
        <View style={styles.cards}>
          <View style={styles.card}><Text style={styles.cardLabel}>Total Sales</Text><Text style={styles.cardValue}>{summary.count}</Text></View>
          <View style={styles.card}><Text style={styles.cardLabel}>Total Revenue</Text><Text style={styles.cardValue}>Rs. {summary.total_revenue.toFixed(2)}</Text></View>
          <View style={styles.card}><Text style={styles.cardLabel}>Cash Revenue</Text><Text style={styles.cardValue}>Rs. {summary.cash_revenue.toFixed(2)}</Text></View>
          <View style={styles.card}><Text style={styles.cardLabel}>Credit Revenue</Text><Text style={styles.cardValue}>Rs. {summary.credit_revenue.toFixed(2)}</Text></View>
        </View>
        <View style={styles.tableHeader}>
          <Text style={[styles.c1, styles.th]}>Time</Text>
          <Text style={[styles.c2, styles.th]}>Customer</Text>
          <Text style={[styles.c3, styles.th]}>Cashier</Text>
          <Text style={[styles.c4, styles.th]}>Items</Text>
          <Text style={[styles.c5, styles.th]}>Total</Text>
          <Text style={[styles.c6, styles.th]}>Payment</Text>
        </View>
        {summary.sales.map((s: any, i: number) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.c1}>{new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Colombo', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(s.created_at))}</Text>
            <Text style={styles.c2}>{s.customer_name}</Text>
            <Text style={styles.c3}>{s.cashier_name}</Text>
            <Text style={styles.c4}>{s.items_count}</Text>
            <Text style={styles.c5}>Rs. {Number(s.total_amount).toFixed(2)}</Text>
            <Text style={styles.c6}>{s.payment_type}</Text>
          </View>
        ))}
      </Page>
    </Document>
  )
}

export default function DailyReportPdf({ date, summary }: Props) {
  return (
    <PDFDownloadLink document={<DailyDocument date={date} summary={summary} />} fileName={`daily-report-${date}.pdf`}>
      {({ loading }) => (
        <button className="inline-flex items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50" disabled={loading}>
          {loading ? 'Preparing…' : 'Export PDF'}
        </button>
      )}
    </PDFDownloadLink>
  )
}
