'use client'

import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1a1a1a' },
  title: { fontSize: 16, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 11, color: '#6b7280', marginBottom: 16 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: '6 4', borderBottom: '1 solid #e5e7eb' },
  tableRow: { flexDirection: 'row', padding: '5 4', borderBottom: '1 solid #f3f4f6' },
  th: { fontFamily: 'Helvetica-Bold', fontSize: 9, color: '#374151' },
  c1: { flex: 3 }, c2: { flex: 2 }, c3: { flex: 2 }, c4: { width: 60, textAlign: 'right' }, c5: { width: 70, textAlign: 'right' }, c6: { flex: 2 },
})

type Props = { products: any[] }

function LowStockDocument({ products }: Props) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.title}>Low Stock Report</Text>
        <Text style={styles.subtitle}>{products.length} products below reorder level · Generated by Lahiru Hardware</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.c1, styles.th]}>Product Name</Text>
          <Text style={[styles.c2, styles.th]}>SKU</Text>
          <Text style={[styles.c3, styles.th]}>Category</Text>
          <Text style={[styles.c4, styles.th]}>Stock</Text>
          <Text style={[styles.c5, styles.th]}>Reorder Level</Text>
          <Text style={[styles.c6, styles.th]}>Supplier</Text>
        </View>
        {products.map((p: any, i: number) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.c1}>{p.name}</Text>
            <Text style={styles.c2}>{p.sku}</Text>
            <Text style={styles.c3}>{p.categories?.name ?? '—'}</Text>
            <Text style={styles.c4}>{p.stock_quantity} {p.unit}</Text>
            <Text style={styles.c5}>{p.reorder_level}</Text>
            <Text style={styles.c6}>{p.suppliers?.name ?? '—'}</Text>
          </View>
        ))}
      </Page>
    </Document>
  )
}

export default function LowStockReportPdf({ products }: Props) {
  return (
    <PDFDownloadLink document={<LowStockDocument products={products} />} fileName="low-stock-report.pdf">
      {({ loading }) => (
        <button className="inline-flex items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50" disabled={loading}>
          {loading ? 'Preparing…' : 'Export PDF'}
        </button>
      )}
    </PDFDownloadLink>
  )
}
