'use client'

import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1a1a1a' },
  title: { fontSize: 16, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 11, color: '#6b7280', marginBottom: 16 },
  cards: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  card: { flex: 1, border: '1 solid #e5e7eb', borderRadius: 4, padding: 8 },
  cardLabel: { fontSize: 9, color: '#6b7280', marginBottom: 2 },
  cardValue: { fontSize: 13, fontFamily: 'Helvetica-Bold' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: '6 4', borderBottom: '1 solid #e5e7eb' },
  tableRow: { flexDirection: 'row', padding: '5 4', borderBottom: '1 solid #f3f4f6' },
  th: { fontFamily: 'Helvetica-Bold', fontSize: 9, color: '#374151' },
  c1: { flex: 2 }, c2: { width: 70, textAlign: 'right' }, c3: { width: 80, textAlign: 'right' }, c4: { width: 80, textAlign: 'right' }, c5: { width: 80, textAlign: 'right' },
})

type Props = {
  year: number
  month: number
  summary: { total_sales: number; total_revenue: number; avg_daily_revenue: number; days: any[] }
}

function MonthlyDocument({ year, month, summary }: Props) {
  const label = `${year}-${String(month).padStart(2, '0')}`
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Monthly Sales Report</Text>
        <Text style={styles.subtitle}>Month: {label} · Generated by Lahiru Hardware</Text>
        <View style={styles.cards}>
          <View style={styles.card}><Text style={styles.cardLabel}>Total Sales</Text><Text style={styles.cardValue}>{summary.total_sales}</Text></View>
          <View style={styles.card}><Text style={styles.cardLabel}>Total Revenue</Text><Text style={styles.cardValue}>Rs. {summary.total_revenue.toFixed(2)}</Text></View>
          <View style={styles.card}><Text style={styles.cardLabel}>Avg Daily Revenue</Text><Text style={styles.cardValue}>Rs. {summary.avg_daily_revenue.toFixed(2)}</Text></View>
        </View>
        <View style={styles.tableHeader}>
          <Text style={[styles.c1, styles.th]}>Date</Text>
          <Text style={[styles.c2, styles.th]}>Sales</Text>
          <Text style={[styles.c3, styles.th]}>Cash Total</Text>
          <Text style={[styles.c4, styles.th]}>Credit Total</Text>
          <Text style={[styles.c5, styles.th]}>Daily Total</Text>
        </View>
        {summary.days.map((d: any, i: number) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.c1}>{d.date}</Text>
            <Text style={styles.c2}>{d.sales_count}</Text>
            <Text style={styles.c3}>Rs. {Number(d.cash_total).toFixed(2)}</Text>
            <Text style={styles.c4}>Rs. {Number(d.credit_total).toFixed(2)}</Text>
            <Text style={styles.c5}>Rs. {Number(d.daily_total).toFixed(2)}</Text>
          </View>
        ))}
      </Page>
    </Document>
  )
}

export default function MonthlyReportPdf({ year, month, summary }: Props) {
  const label = `${year}-${String(month).padStart(2, '0')}`
  return (
    <PDFDownloadLink document={<MonthlyDocument year={year} month={month} summary={summary} />} fileName={`monthly-report-${label}.pdf`}>
      {({ loading }) => (
        <button className="inline-flex items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50" disabled={loading}>
          {loading ? 'Preparing…' : 'Export PDF'}
        </button>
      )}
    </PDFDownloadLink>
  )
}
